config/routes.rb
Treebook::Application.routes.draw do
  resources :user_profiles

  devise_for :users
  
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register 
    get 'login', to: 'devise/sessions#new', as: :login 
    get 'logout', to: 'devise/sessions#destroy', as: :logout 
  end

  resources :statuses
  root to: 'statuses#index'

  get '/:id' , to: 'user_profiles#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user

	validates :content, presence:  true,
						length: {minimum: 2}

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses

         
  ROLES = %w[admin moderator author banned]

  validates :first_name, presence: true

  validates :last_name, presence:true

  validates :profile_name, presence:true, uniqueness: true,
                  format: {
                    with: /a-zA-Z0-9_~/,
                    message: 'Must be formatted'

                  }



  def full_name
  	full_name + " " + last_name
  end

  def gravatar_url
  		stripped_email = email.strip
  		downcased_email = stripped_email.downcase
  		hash = Digest::MD5.hexdigest(downcased_email)

  		"http://gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name,:profile_name, :email, :password, :password_confirmation) }
  end

  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    @status = current_user.statuses.new(status_params)
    if params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
      end

    respond_to do |format|
      if @status.update_attributes(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
			when :alert
				"alert-error"
			when :notice
				"alert-success"
			else
				""
			end
			
		end

end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paikse Mpalitsa</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a  class="brand " href="#">Paikse Mpalitsa</a>
				<ul class="nav">
					<li><%= link_to "Posts", statuses_path %></a></li>
					
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to current_user.first_name, edit_user_registration_path %></li>
						<li><%= link_to 'Profil', new_user_profile_path %></li>
						<li><%= link_to 'Log out', logout_path %></li>
					<% else %>
						<li><%= link_to "Register", register_path %> </li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="container">
		<% flash.each do |type, message| %>
	    	<div class="alert <%= flash_class type %>">
	    		<button class="close" data-dismiss="alert">X</button>
	    		<%= message %>
	    	</div>
	    <% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All Posts</h1>
</div>

 <%= if user_signed_in? 
     link_to "Post a new status", new_status_path, class:"btn-success" 
   end 
 %>

<% @statuses.each do |status| %>

<div class="status">
  <div class="row">
    <div class="span1">
        <%= image_tag status.user.gravatar_url %>
    </div>
  <div class="span7">
  <strong>Name:</strong>
  <%= status.user.profile_name %>
  <P><%= status.content %></P>
    <div class="meta">
      <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
        <% if user_signed_in? %>
          |<%= link_to "Edit", edit_status_path(status) %>
          |<%= link_to "Delete", status, method: :delete ,data: {confirm: "Are you sure want to delete this status"} %>
        <% end %>
        </span>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.profile_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>